# Generated by Django 4.2.3 on 2023-08-10 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auctionbids_auctionlisting_auctionlistingcomments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auctionlisting',
            old_name='owner',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='auctionlisting',
            name='bids',
        ),
    ]
