# Generated by Django 4.2.3 on 2023-08-10 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_rename_owner_auctionlisting_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionlisting',
            name='user',
        ),
    ]
