# Generated by Django 4.2.3 on 2023-08-10 12:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_remove_auctionlisting_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auctionbids',
            old_name='owner',
            new_name='bidder',
        ),
        migrations.RenameField(
            model_name='auctionlistingcomments',
            old_name='user',
            new_name='creator',
        ),
        migrations.AddField(
            model_name='auctionbids',
            name='auction',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='auctions.auctionlisting'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auctionlisting',
            name='creator',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
