# Generated by Django 4.2.3 on 2023-08-10 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_rename_owner_auctionbids_bidder_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auctionlisting',
            old_name='price',
            new_name='starting_bid',
        ),
        migrations.AddField(
            model_name='auctionlisting',
            name='category',
            field=models.CharField(default='Toys', max_length=64),
        ),
        migrations.AddField(
            model_name='auctionlisting',
            name='image_url',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
